benchmark/latency: add Grpcbug test
This test emulates the setup for the unexpected EOF bug that can be hit with the setup
https://github.com/brianneville/grpcbug.
It uses the same proto service, request, and response.
Unfortunately right now, this test fails to reproduce the bug.

go.mod was set to use go1.16 so that //go:embed would work

test results:

benchmark/latency % go test
--- FAIL: Test (1.03s)
    --- FAIL: Test/Grpcbug (0.01s)
        tlogger.go:116: INFO server.go:598 [core] [Server #1] Server created  (t=+1.976177ms)
        tlogger.go:116: INFO grpcbug_test.go:94 [core] [Channel #2] Channel created  (t=+2.019801ms)
        tlogger.go:116: INFO clientconn.go:1579 [core] [Channel #2] original dial target is: "127.0.0.1:50125"  (t=+2.055983ms)
        tlogger.go:116: INFO clientconn.go:1584 [core] [Channel #2] dial target "127.0.0.1:50125" parse failed: parse "127.0.0.1:50125": first path segment in URL cannot contain colon  (t=+2.07645ms)
        tlogger.go:116: INFO server.go:786 [core] [Server #1 ListenSocket #3] ListenSocket created  (t=+2.087706ms)
        tlogger.go:116: INFO clientconn.go:1599 [core] [Channel #2] fallback to scheme "passthrough"  (t=+2.10609ms)
        tlogger.go:116: INFO clientconn.go:1607 [core] [Channel #2] parsed dial target is: {Scheme:passthrough Authority: Endpoint:127.0.0.1:50125 URL:{Scheme:passthrough Opaque: User: Host: Path:/127.0.0.1:50125 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}  (t=+2.145245ms)
        tlogger.go:116: INFO clientconn.go:263 [core] [Channel #2] Channel authority set to "127.0.0.1:50125"  (t=+2.172746ms)
        tlogger.go:116: INFO resolver_conn_wrapper.go:175 [core] [Channel #2] Resolver state updated: {
              "Addresses": [
                {
                  "Addr": "127.0.0.1:50125",
                  "ServerName": "",
                  "Attributes": null,
                  "BalancerAttributes": null,
                  "Type": 0,
                  "Metadata": null
                }
              ],
              "ServiceConfig": null,
              "Attributes": null
            } (resolver returned new addresses)  (t=+2.28414ms)
        tlogger.go:116: INFO balancer_conn_wrappers.go:271 [core] [Channel #2] Channel switches to new LB policy "pick_first"  (t=+2.321633ms)
        tlogger.go:116: INFO clientconn.go:725 [core] [Channel #2 SubChannel #4] Subchannel created  (t=+2.339342ms)
        tlogger.go:116: INFO clientconn.go:1101 [core] [Channel #2 SubChannel #4] Subchannel Connectivity change to CONNECTING  (t=+2.373285ms)
        tlogger.go:116: INFO clientconn.go:1212 [core] [Channel #2 SubChannel #4] Subchannel picks a new address "127.0.0.1:50125" to connect  (t=+2.392032ms)
        tlogger.go:116: INFO clientconn.go:418 [core] [Channel #2] Channel Connectivity change to CONNECTING  (t=+2.431147ms)
        tlogger.go:116: INFO picker_wrapper.go:161 [core] blockingPicker: the picked transport is not ready, loop back to repick  (t=+2.465381ms)
        tlogger.go:116: INFO syscall_nonlinux.go:39 [core] CPU time info is unavailable on non-linux environments.  (t=+3.161936ms)
        tlogger.go:116: INFO clientconn.go:1101 [core] [Channel #2 SubChannel #4] Subchannel Connectivity change to READY  (t=+3.280603ms)
        tlogger.go:116: INFO clientconn.go:418 [core] [Channel #2] Channel Connectivity change to READY  (t=+3.312295ms)
        grpcbug_test.go:113: expected to get error "rpc error: code = Internal desc = unexpected EOF", instead got error %!q(<nil>) with response of length 275075
        tlogger.go:116: INFO clientconn.go:418 [core] [Channel #2] Channel Connectivity change to SHUTDOWN  (t=+5.920925ms)
        tlogger.go:116: INFO clientconn.go:1101 [core] [Channel #2 SubChannel #4] Subchannel Connectivity change to SHUTDOWN  (t=+5.944169ms)
        tlogger.go:116: INFO clientconn.go:1457 [core] [Channel #2 SubChannel #4] Subchannel deleted  (t=+5.955453ms)
        tlogger.go:116: INFO clientconn.go:1056 [core] [Channel #2] Channel deleted  (t=+5.963342ms)
        tlogger.go:116: INFO server.go:737 [core] [Server #1 ListenSocket #3] ListenSocket deleted  (t=+5.996876ms)
FAIL
exit status 1
FAIL    google.golang.org/grpc/benchmark/latency        1.645s